name: publish
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        description: Optionally override the tag
        default: auto
      bump:
        type: choice
        required: false
        description: Optionally override the semantic version bump
        default: auto
        options:
          - auto
          - MAJOR
          - MINOR
          - PATCH
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.6.1
      - name: Install dependencies
        run: poetry install
      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run inv publish --tag ${{ inputs.tag }} --bump ${{ inputs.bump }}
